#
# rustfmt.toml
#
# Documentation: https://rust-lang.github.io/rustfmt/
#

blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
comment_width = 109
condense_wildcard_suffixes = true
doc_comment_code_block_width = 109
edition = "2021"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
hex_literal_case = "Lower"
group_imports = "StdExternalCrate"
imports_granularity = "Item"
imports_layout = "HorizontalVertical"
match_arm_blocks = false
max_width = 109
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
skip_macro_invocations = [
  "dbg", "eprint", "eprintln", "format", "print", "println", "process_error", "process_note", "process_warn",
  "write", "writeln"
]
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true

# EOF
