#
# ci.yml
#

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings" # Fail on warnings, including Clippy lints

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: clippy
    - name: Build
      run: cargo build --verbose
    # Run "Clippy" on Ubuntu only---one platform is enough 
    - name: Clippy
      run: cargo +nightly clippy --all-targets --all-features
    # Run "Doc" on Ubuntu only---one platform is enough 
    - name: Doc
      run: cargo doc --all-features --no-deps
    - name: Test
      run: cargo test --verbose
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose

# EOF
