#
# ci.yml
#

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings" # Fail on warnings, including Clippy lints

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose

# EOF
